jenkins:
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: "false"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "GitHub"
          id: "GITHUB"
          password: ${GIT_PASSWORD}
          scope: GLOBAL
          username: ${GIT_USER}
      - basicSSHUserPrivateKey:
          description: "Heroku"
          id: "HEROKU"
          privateKeySource:
            directEntry:
              privateKey: ${HEROKU_SSH}
          scope: GLOBAL
jobs:
  - script: >
      job('SeedJob') {
          scm {
              git {
                  remote {
                      name('Github')
                      url('https://github.com/raqulec/dsl_scripts.git')
                      credentials('GITHUB')
                  }
              }
          }
          steps {
              dsl {
                  external('**/*.groovy')
              }
          }
          triggers {
              upstream('StartupTrigger', 'SUCCESS')
          }
      }
  - script: >
      job('StartupTrigger') {
          triggers {
              hudsonStartupTrigger {
                  label('')
                  quietPeriod('')
                  nodeParameterName('')
                  runOnChoice('')
              } 
          }
      }